spring:
  application:
    name: microscope
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    driver-class-name: org.sqlite.JDBC
    username: dev
    password: dev
    url: 'jdbc:sqlite:temp.db'
server:
  port: 8080